export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_CLIENT_CONFIG = 'SET_CLIENT_CONFIG'
export const SET_API_VERSION =  'SET_API_VERSION'
export const UPDATE_NETWORK_DATA =  'UPDATE_NETWORK_DATA'